app01/urls.py
from django.urls import path
from app01.views import *

urlpatterns = [
    path('index/',index),
    path('addPerson/',addperson),
    path('queryPerson/',queryperson),
    path('updatePerson/',updateperson),
    path('removePerson/',removeperson),

    path('addmore/',addmore),
    path('querymore/',querymore),
    path('updatemore/',updatemore),
    path('removemore/',removemore),

    path('addmany/',addmany),
    path('querymany/',querymany),
    path('updatemany/',updatemany),
    path('removemany/',removemany),

    path('juhe/',juhe),
    path('Ffunc/',Ffunc),
    path('Qfunc/',Qfunc),
]

study/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from . import views
# import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', views.about),
    path('index/', views.index),
    path('listpic/',views.listpic),
    path('newslistpic/', views.newslistpic),
    re_path('newslistpic/(\d+)', views.newslistpic),
    path('app01/', include('app01.urls')),
    re_path('details/(\d+)',views.details),
    path('ckeditor/',include('ckeditor_uploader.urls')),

    path('reqtest',views.reqtest),
    # path('register/',views.register),
    path('ajax_get/',views.ajax_get),
    path('ajax_get_data/',views.ajax_get_data),
    path('ajax_post/',views.ajax_post),
    path('ajax_post_data/',views.ajax_post_data),
    path('one_cookie/',views.one_cookie),

    #########################后台路由
    path('register/',views.Register.as_view()),
    path('login/',views.Login.as_view()),
    path('h_index/',views.Index.as_view()),
    path('yanzhengma/',views.yanzhengma),
    path('logout/',views.logout),
    path('personal/',views.personal),
    re_path('myarticles/(\d+)',views.myarticles),
    re_path('myarticle/(\d+)',views.myarticle),
]

app01/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.

class Person(models.Model):
    name = models.CharField(max_length=32,verbose_name="姓名")
    age = models.IntegerField(verbose_name="年龄")
    height = models.DecimalField(max_digits=5,decimal_places=2,verbose_name="身高")
    birthday = models.DateField(auto_now=True,verbose_name="生日")
    def __str__(self):
        return self.name
    class Meta:
        db_table = "person"
        verbose_name = "用户"
        verbose_name_plural = verbose_name
class Publish(models.Model):
    name = models.CharField(max_length=32)
    address = models.CharField(max_length=32)
    class Meta:
        db_table = "publish"
class Book(models.Model):
    name = models.CharField(max_length=32)
    publish = models.ForeignKey(to=Publish,on_delete=models.CASCADE)
    num = models.IntegerField(default=200)
    saled = models.IntegerField(default=100)
    class Meta:
        db_table = "book"
class Teacher(models.Model):
    name = models.CharField(max_length=32)
    age = models.IntegerField(default=30)
    gender = models.CharField(max_length=32)
    person = models.ManyToManyField(to=Person)
    class Meta:
        db_table = "teacher"

GENDER_LIST = (
    (1,'男'),
    (2,'女'),
)
class Author(models.Model):
    name = models.CharField(max_length=32,verbose_name="姓名")
    password = models.CharField(max_length=64,default=123)
    age = models.IntegerField(verbose_name="年龄")
    gender = models.IntegerField(choices=GENDER_LIST,default=1,verbose_name="性别")
    email = models.CharField(max_length=32,verbose_name="邮箱")
    def __str__(self):
        return self.name
    class Meta:
        db_table = "author"
        verbose_name = "作者表"
        verbose_name_plural = verbose_name
class Type(models.Model):
    type_name = models.CharField(max_length=32,verbose_name="类型")
    description = RichTextField(verbose_name="描述")
    def __str__(self):
        return self.type_name
    class Meta:
        db_table = "type"
        verbose_name = "类型表"
        verbose_name_plural = verbose_name
class Article(models.Model):
    title = models.CharField(max_length=32)
    date = models.DateField(auto_now=True)
    content = RichTextField(verbose_name="内容")
    description = RichTextField(verbose_name="描述")
    picture = models.ImageField(upload_to='images')
    recommend = models.IntegerField(default=0,verbose_name="推荐")
    click = models.IntegerField(default=0,verbose_name="点击率")
    author = models.ForeignKey(to=Author,on_delete=models.PROTECT,verbose_name="作者")
    type = models.ManyToManyField(to=Type,verbose_name="类型")
    def __str__(self):
        return self.title
    class Meta:
        db_table = "article"
        verbose_name = "文章表"
        verbose_name_plural = verbose_name

class User(models.Model):
    name = models.CharField(max_length=32)
    password = models.CharField(max_length=32)
    class Meta:
        db_table = 'user'

templates/saller/base2.html
<!doctype html>
<html>
<head>
<meta charset="utf8">
<title>个人博客模板古典系列之――江南墨卷</title>
<meta name="keywords" content="个人博客模板古典系列之――江南墨卷" />
<meta name="description" content="个人博客模板古典系列之――江南墨卷" />
<link href="/static/css/base.css" rel="stylesheet">
<link href="/static/css/main.css" rel="stylesheet">
<!--[if lt IE 9]>
<script src="/static/js/modernizr.js"></script>
<![endif]-->
<script type="text/javascript" src="/static/js/jquery.js"></script>
{% block js_css %}

{% endblock %}

<body>
<div id="wrapper">

{% block content %}

{% endblock %}

</div>
</body>
</html>

templates/saller/details.html
{% extends "saller/base2.html" %}

{% block content %}
    <div class="container" style="margin-top: 100px">
    <div class="con_content">
      <div class="about_box">
        <div class="f_box">
          <p class="a_title">{{ article.title }}</p>
          <p class="p_title"></p>
          <!--  <p class="box_p"><span>发布时间：2017-07-07 15:12:42</span><span>作者：唐孝文</span><span>来源：稽查支队</span><span>点击：111056</span></p>-->
          <!-- 可用于内容模板 -->
        </div>
        <ul class="about_content">
          <p> {{ article.content |safe }}</p>
          <p><img src="/static/{{ article.picture }}" width="800px"></p>
        </ul>
        <!--    <div class="nextinfos">
      <p>上一篇：<a href="/">区中医医院开展志愿服务活动</a></p>
      <p>下一篇：<a href="/">广安区批准“单独两孩”500例</a></p>
    </div>-->
        <!-- 可用于内容模板 -->

        <!-- container代码 结束 -->
      </div>
    </div>
    <div class="blank"></div>
  </div>
{% endblock %}

templates/saller/index.html
{% extends 'saller/base.html' %}
{% block content %}

          <!-- Page Heading -->
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
            <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>
          </div>

          <!-- Content Row -->
          <div class="row">

            <!-- Earnings (Monthly) Card Example -->
            <div class="col-xl-3 col-md-6 mb-4">
              <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Earnings (Monthly)</div>
                      <div class="h5 mb-0 font-weight-bold text-gray-800">$40,000</div>
                    </div>
                    <div class="col-auto">
                      <i class="fas fa-calendar fa-2x text-gray-300"></i>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <!-- Earnings (Monthly) Card Example -->
            <div class="col-xl-3 col-md-6 mb-4">
              <div class="card border-left-success shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-success text-uppercase mb-1">Earnings (Annual)</div>
                      <div class="h5 mb-0 font-weight-bold text-gray-800">$215,000</div>
                    </div>
                    <div class="col-auto">
                      <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <!-- Earnings (Monthly) Card Example -->
            <div class="col-xl-3 col-md-6 mb-4">
              <div class="card border-left-info shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Tasks</div>
                      <div class="row no-gutters align-items-center">
                        <div class="col-auto">
                          <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">50%</div>
                        </div>
                        <div class="col">
                          <div class="progress progress-sm mr-2">
                            <div class="progress-bar bg-info" role="progressbar" style="width: 50%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="col-auto">
                      <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <!-- Pending Requests Card Example -->
            <div class="col-xl-3 col-md-6 mb-4">
              <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">Pending Requests</div>
                      <div class="h5 mb-0 font-weight-bold text-gray-800">18</div>
                    </div>
                    <div class="col-auto">
                      <i class="fas fa-comments fa-2x text-gray-300"></i>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <!-- Content Row -->

          <div class="row">

            <!-- Area Chart -->
            <div class="col-xl-8 col-lg-7">
              <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Earnings Overview</h6>
                  <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                      <div class="dropdown-header">Dropdown Header:</div>
                      <a class="dropdown-item" href="#">Action</a>
                      <a class="dropdown-item" href="#">Another action</a>
                      <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                  </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                  <div class="chart-area">
                    <canvas id="myAreaChart"></canvas>
                  </div>
                </div>
              </div>
            </div>

            <!-- Pie Chart -->
            <div class="col-xl-4 col-lg-5">
              <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Revenue Sources</h6>
                  <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                      <div class="dropdown-header">Dropdown Header:</div>
                      <a class="dropdown-item" href="#">Action</a>
                      <a class="dropdown-item" href="#">Another action</a>
                      <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                  </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                  <div class="chart-pie pt-4 pb-2">
                    <canvas id="myPieChart"></canvas>
                  </div>
                  <div class="mt-4 text-center small">
                    <span class="mr-2">
                      <i class="fas fa-circle text-primary"></i> Direct
                    </span>
                    <span class="mr-2">
                      <i class="fas fa-circle text-success"></i> Social
                    </span>
                    <span class="mr-2">
                      <i class="fas fa-circle text-info"></i> Referral
                    </span>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <!-- Content Row -->
          <div class="row">

            <!-- Content Column -->
            <div class="col-lg-6 mb-4">

              <!-- Project Card Example -->
              <div class="card shadow mb-4">
                <div class="card-header py-3">
                  <h6 class="m-0 font-weight-bold text-primary">Projects</h6>
                </div>
                <div class="card-body">
                  <h4 class="small font-weight-bold">Server Migration <span class="float-right">20%</span></h4>
                  <div class="progress mb-4">
                    <div class="progress-bar bg-danger" role="progressbar" style="width: 20%" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                  <h4 class="small font-weight-bold">Sales Tracking <span class="float-right">40%</span></h4>
                  <div class="progress mb-4">
                    <div class="progress-bar bg-warning" role="progressbar" style="width: 40%" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                  <h4 class="small font-weight-bold">Customer Database <span class="float-right">60%</span></h4>
                  <div class="progress mb-4">
                    <div class="progress-bar" role="progressbar" style="width: 60%" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                  <h4 class="small font-weight-bold">Payout Details <span class="float-right">80%</span></h4>
                  <div class="progress mb-4">
                    <div class="progress-bar bg-info" role="progressbar" style="width: 80%" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                  <h4 class="small font-weight-bold">Account Setup <span class="float-right">Complete!</span></h4>
                  <div class="progress">
                    <div class="progress-bar bg-success" role="progressbar" style="width: 100%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                </div>
              </div>

              <!-- Color System -->
              <div class="row">
                <div class="col-lg-6 mb-4">
                  <div class="card bg-primary text-white shadow">
                    <div class="card-body">
                      Primary
                      <div class="text-white-50 small">#4e73df</div>
                    </div>
                  </div>
                </div>
                <div class="col-lg-6 mb-4">
                  <div class="card bg-success text-white shadow">
                    <div class="card-body">
                      Success
                      <div class="text-white-50 small">#1cc88a</div>
                    </div>
                  </div>
                </div>
                <div class="col-lg-6 mb-4">
                  <div class="card bg-info text-white shadow">
                    <div class="card-body">
                      Info
                      <div class="text-white-50 small">#36b9cc</div>
                    </div>
                  </div>
                </div>
                <div class="col-lg-6 mb-4">
                  <div class="card bg-warning text-white shadow">
                    <div class="card-body">
                      Warning
                      <div class="text-white-50 small">#f6c23e</div>
                    </div>
                  </div>
                </div>
                <div class="col-lg-6 mb-4">
                  <div class="card bg-danger text-white shadow">
                    <div class="card-body">
                      Danger
                      <div class="text-white-50 small">#e74a3b</div>
                    </div>
                  </div>
                </div>
                <div class="col-lg-6 mb-4">
                  <div class="card bg-secondary text-white shadow">
                    <div class="card-body">
                      Secondary
                      <div class="text-white-50 small">#858796</div>
                    </div>
                  </div>
                </div>
              </div>

            </div>

            <div class="col-lg-6 mb-4">

              <!-- Illustrations -->
              <div class="card shadow mb-4">
                <div class="card-header py-3">
                  <h6 class="m-0 font-weight-bold text-primary">Illustrations</h6>
                </div>
                <div class="card-body">
                  <div class="text-center">
                    <img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 25rem;" src="/static/img/undraw_posting_photo.svg" alt="">
                  </div>
                  <p>Add some quality, svg illustrations to your project courtesy of <a target="_blank" rel="nofollow" href="https://undraw.co/">unDraw</a>, a constantly updated collection of beautiful svg images that you can use completely free and without attribution!</p>
                  <a target="_blank" rel="nofollow" href="https://undraw.co/">Browse Illustrations on unDraw &rarr;</a>
                </div>
              </div>

              <!-- Approach -->
              <div class="card shadow mb-4">
                <div class="card-header py-3">
                  <h6 class="m-0 font-weight-bold text-primary">Development Approach</h6>
                </div>
                <div class="card-body">
                  <p>SB Admin 2 makes extensive use of Bootstrap 4 utility classes in order to reduce CSS bloat and poor page performance. Custom CSS classes are used to create custom components and custom utility classes.</p>
                  <p class="mb-0">Before working with this theme, you should become familiar with the Bootstrap framework, especially the utility classes.</p>
                </div>
              </div>

            </div>
          </div>
{% endblock %}

templates/saller/login.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>SB Admin 2 - Register</title>

  <!-- Custom fonts for this template-->
  <link href="/static/saller/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="/static/saller/css/sb-admin-2.min.css" rel="stylesheet">
    <script src="/static/js/vue-resource.js"></script>
    <script src="/static/js/vue.min.js"></script>

</head>

<body class="bg-gradient-primary">

  <div class="container">

    <div class="card o-hidden border-0 shadow-lg my-5">
      <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
          <div class="col-lg-5 d-none d-lg-block bg-login-image"></div>
          <div class="col-lg-7">
            <div class="p-5">
              <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">登录</h1>
              </div>
              <form class="user" method="post">
                {% csrf_token %}
                <div class="form-group">
                  <input type="email" name="email" class="form-control form-control-user" id="exampleInputEmail" placeholder="邮箱">
                </div>
                <div class="form-group row">
                  <div class="col-sm-12 mb-3 mb-sm-0">
                    <input type="password" name='password' class="form-control form-control-user" id="exampleInputPassword" placeholder="密码">
                  </div>
                </div>
                  <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    <input type="text" name='yanzhengma' id="yan" class="form-control form-control-user" placeholder="验证码">
                  </div>
                   <div class="col-sm-6 mb-3 mb-sm-0">

                    <img src="/yanzhengma/" id="img" >

                  </div>
                </div>
                <input href="/register/" value="登录" type="submit" class="btn btn-primary btn-user btn-block">

              </form>
              <hr>
              <div class="text-center">
                <a class="small" href="/register/">没有账号去注册</a>
                <p class="small" href="/login/">{{ ret }}</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="/static/saller/vendor/jquery/jquery.min.js"></script>
  <script src="/static/saller/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Core plugin JavaScript-->
  <script src="/static/saller/vendor/jquery-easing/jquery.easing.min.js"></script>

  <!-- Custom scripts for all pages-->
  <script src="/static/js/sb-admin-2.min.js"></script>
  <script>
        $('#img').click(function () {
            this.src += '?'
        })
  </script>

</body>

</html>

templates/saller/myarticles.html
{% extends 'saller/base.html' %}
{% block style %}
    <link href="/static/css/base.css" rel="stylesheet">
<link href="/static/css/main.css" rel="stylesheet">
<!--[if lt IE 9]>
<script src="js/modernizr.js"></script>
<![endif]-->
<script type="text/javascript" src="js/jquery.js"></script>
{% endblock %}
{% block  content%}
<div class="dtxw box">
{% for article in page_obj %}
        <li>
          <div class="dttext f_l">
            <ul>
              <h2><a href="/myarticle/{{ article.id }}">{{ article.title }}</a></h2>
              <p>{{ article.description | safe}}</p>
              <span>{{ article.date }}</span>
            </ul>
          </div>
          <div class="xwpic f_r"><a href="/"><img src="/static/{{ article.picture }}"></a></div>
        </li>
{% endfor %}
      </div>
    <div class="pagelist">
        <a href="/myarticles/1">首页</a>
        {% if page_obj.has_previous %}
            <a href="/myarticles/{{ page_obj.previous_page_number }}">上一页</a>
        {% endif %}
            {% for one in page_range %}
                <a href="/myarticles/{{ one }}">{{ one }}</a>
            {% endfor %}
        {% if page_obj.has_next %}
           <a href="/myarticles/{{ page_obj.next_page_number }}">下一页</a>
        {% endif %}
         <a href="/myarticles/{{ max_page }}">尾页</a>
        </div>
{% endblock %}

templates/saller/personal.html
{% extends 'saller/base.html' %}
{% block  content%}
<!DOCTYPE html>

<html lang="en-us" >
<head>
<link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">
<link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css">
<script type="text/javascript" src="/admin/jsi18n/"></script>
<script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
<script type="text/javascript" src="/static/ckeditor/ckeditor-init.js" data-ckeditor-basepath="/static/ckeditor/ckeditor/" id="ckeditor-init-script"></script>
<script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
<script type="text/javascript" src="/static/ckeditor/ckeditor/ckeditor.js"></script>
<script type="text/javascript" src="/static/admin/js/core.js"></script>
<script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
<script type="text/javascript" src="/static/admin/js/actions.js"></script>
<script type="text/javascript" src="/static/admin/js/urlify.js"></script>
<script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>
<script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css">


<meta name="robots" content="NONE,NOARCHIVE">
</head>


<body class=" app-app01 model-article change-form"
  data-admin-utc-offset="0">

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
  <fieldset class="module aligned ">



        <div class="form-row field-title">


                <div>


                        <label class="required" for="id_title">文章标题:</label>

                            <input type="text" name="title" required id="id_title" class="vTextField" maxlength="32">



                </div>

        </div>

        <div class="form-row field-content">


                <div>


                        <label class="required" for="id_content">文章内容:</label>

                            <div class="django-ckeditor-widget" data-field-id="id_content" style="display: inline-block;">
    <textarea cols="40" id="id_content" name="content" rows="10" required data-processed="0" data-config="{&quot;toolbar&quot;: &quot;Full&quot;, &quot;filebrowserWindowWidth&quot;: 940, &quot;height&quot;: 291, &quot;skin&quot;: &quot;moono-lisa&quot;, &quot;width&quot;: 835, &quot;toolbar_Full&quot;: [[&quot;Styles&quot;, &quot;Format&quot;, &quot;Bold&quot;, &quot;Italic&quot;, &quot;Underline&quot;, &quot;Strike&quot;, &quot;SpellChecker&quot;, &quot;Undo&quot;, &quot;Redo&quot;], [&quot;Link&quot;, &quot;Unlink&quot;, &quot;Anchor&quot;], [&quot;Image&quot;, &quot;Flash&quot;, &quot;Table&quot;, &quot;HorizontalRule&quot;], [&quot;TextColor&quot;, &quot;BGColor&quot;], [&quot;Smiley&quot;, &quot;SpecialChar&quot;], [&quot;Source&quot;]], &quot;filebrowserWindowHeight&quot;: 725, &quot;language&quot;: &quot;en-us&quot;, &quot;toolbar_Basic&quot;: [[&quot;Source&quot;, &quot;-&quot;, &quot;Bold&quot;, &quot;Italic&quot;]]}" data-external-plugin-resources="[]" data-id="id_content" data-type="ckeditortype"></textarea>
</div>



                </div>

        </div>

        <div class="form-row field-description">


                <div>


                        <label class="required" for="id_description">描述:</label>

                            <div class="django-ckeditor-widget" data-field-id="id_description" style="display: inline-block;">
    <textarea cols="40" id="id_description" name="description" rows="10" required data-processed="0" data-config="{&quot;toolbar&quot;: &quot;Full&quot;, &quot;filebrowserWindowWidth&quot;: 940, &quot;height&quot;: 291, &quot;skin&quot;: &quot;moono-lisa&quot;, &quot;width&quot;: 835, &quot;toolbar_Full&quot;: [[&quot;Styles&quot;, &quot;Format&quot;, &quot;Bold&quot;, &quot;Italic&quot;, &quot;Underline&quot;, &quot;Strike&quot;, &quot;SpellChecker&quot;, &quot;Undo&quot;, &quot;Redo&quot;], [&quot;Link&quot;, &quot;Unlink&quot;, &quot;Anchor&quot;], [&quot;Image&quot;, &quot;Flash&quot;, &quot;Table&quot;, &quot;HorizontalRule&quot;], [&quot;TextColor&quot;, &quot;BGColor&quot;], [&quot;Smiley&quot;, &quot;SpecialChar&quot;], [&quot;Source&quot;]], &quot;filebrowserWindowHeight&quot;: 725, &quot;language&quot;: &quot;en-us&quot;, &quot;toolbar_Basic&quot;: [[&quot;Source&quot;, &quot;-&quot;, &quot;Bold&quot;, &quot;Italic&quot;]]}" data-external-plugin-resources="[]" data-id="id_description" data-type="ckeditortype"></textarea>
</div>



                </div>

        </div>

        <div class="form-row field-picture">
                <div>
                    <label class="required">图片:</label>
                    <input type="file" name="picture">
                </div>
        </div>


        <div class="form-row field-type">


                <div>


                        <label class="required" for="id_type">类型:</label>
                            <div class="related-widget-wrapper">
    <select name="type" required id="id_type" multiple>
  <option value="1">散文</option>

  <option value="2">诗歌</option>

  <option value="3">童话</option>

</select>

</div>
                </div>
        </div>
</fieldset>
<div class="submit-row">
<input type="submit" value="发布" class="default" name="_save">
</div>
</form>
</body>
</html>

{% endblock %}